// dashboard/src/lib/modules/builds/View.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { getStatusClass } from '$lib/utils/formatters';

    let builds = $state<any[]>([]);
    let loading = $state(true);

    async function fetchBuilds() {
        loading = true;
        try {
            const res = await fetch('/api/modules/builds/index');
            builds = await res.json();
        } catch (err) {
            console.error('Builds fetch error:', err);
        } finally {
            loading = false;
        }
    }

    onMount(fetchBuilds);

    function getDotClass(status: string) {
        const cls = getStatusClass(status);
        if (cls === 'status-success') return 'bg-google-green';
        if (cls === 'status-error') return 'bg-google-red';
        if (cls === 'status-warning') return 'bg-google-amber-dark';
        if (cls === 'status-blue') return 'bg-google-blue';
        return 'bg-google-gray-500';
    }
</script>

<div>
    {#if loading}
        <div class="text-google-gray-500 text-[13px] text-center py-6">読み込み中...</div>
    {:else}
        <div class="bg-white border border-google-gray-300 rounded-lg overflow-hidden mb-6">
            <div class="flex justify-between items-center px-4 py-3 border-b border-google-gray-200">
                <h2 class="text-sm font-medium text-google-gray-900 m-0">Cloud Build 履歴</h2>
                <button class="bg-white border-0 text-google-blue text-xs font-medium cursor-pointer hover:underline" onclick={fetchBuilds}>
                    更新
                </button>
            </div>
            <div class="p-0 overflow-x-auto">
                <div class="flex items-center gap-2 px-3 py-2 border-b border-google-gray-300 bg-google-gray-50 text-xs text-google-gray-500">
                    <span>フィルタ</span>
                    <span class="bg-white px-2 py-0.5 rounded text-google-gray-700">プロパティ名または値を入力</span>
                </div>
                <table class="w-full text-left text-[13px] text-google-gray-700 border-collapse">
                    <thead class="bg-google-gray-50">
                        <tr>
                            <th class="px-4 py-2.5 border-b border-google-gray-200 font-medium text-google-gray-500 whitespace-nowrap">ステータス</th>
                            <th class="px-4 py-2.5 border-b border-google-gray-200 font-medium text-google-gray-500 whitespace-nowrap">ビルド</th>
                            <th class="px-4 py-2.5 border-b border-google-gray-200 font-medium text-google-gray-500 whitespace-nowrap">リージョン</th>
                            <th class="px-4 py-2.5 border-b border-google-gray-200 font-medium text-google-gray-500 whitespace-nowrap">ソース</th>
                            <th class="px-4 py-2.5 border-b border-google-gray-200 font-medium text-google-gray-500 whitespace-nowrap">Ref</th>
                            <th class="px-4 py-2.5 border-b border-google-gray-200 font-medium text-google-gray-500 whitespace-nowrap">commit</th>
                            <th class="px-4 py-2.5 border-b border-google-gray-200 font-medium text-google-gray-500 whitespace-nowrap">トリガー名</th>
                        </tr>
                    </thead>
                    <tbody>
                        {#each builds as build}
                            <tr class="border-b border-google-gray-200 hover:bg-google-gray-50 last:border-b-0">
                                <td class="px-4 py-3 align-top whitespace-nowrap">
                                    <span class="inline-flex items-center gap-2 text-xs font-medium {getStatusClass(build.status)}">
                                        <span class="w-2.5 h-2.5 rounded-full {getDotClass(build.status)}"></span>
                                        {build.status}
                                    </span>
                                </td>
                                <td class="px-4 py-3 align-top whitespace-nowrap">
                                    <a href="#" class="text-google-blue font-medium hover:underline">{build.id}</a>
                                </td>
                                <td class="px-4 py-3 align-top whitespace-nowrap">{build.region}</td>
                                <td class="px-4 py-3 align-top whitespace-nowrap"><a href="#" class="text-google-blue hover:underline">{build.source || 'GitHub'}</a></td>
                                <td class="px-4 py-3 align-top whitespace-nowrap">{build.ref || 'main'}</td>
                                <td class="px-4 py-3 align-top whitespace-nowrap"><a href="#" class="text-google-blue hover:underline">{build.commit}</a></td>
                                <td class="px-4 py-3 align-top whitespace-nowrap"><a href="#" class="text-google-blue hover:underline">{build.triggerName || ''}</a></td>
                            </tr>
                        {/each}
                    </tbody>
                </table>
            </div>
        </div>
    {/if}
</div>

// dashboard/client/src/modules/builds/View.tsx
import React, { useEffect, useState } from 'react';

interface Build {
    id: string;
    status: string;
    source: string;
    ref: string;
    commit: string;
    triggerName: string;
}

const BuildsView: React.FC = () => {
    const [builds, setBuilds] = useState<Build[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetch('/api/modules/builds')
            .then(res => res.json())
            .then(data => {
                setBuilds(data);
                setLoading(false);
            })
            .catch(err => {
                console.error('Builds fetch error:', err);
                setLoading(false);
            });
    }, []);

    if (loading) return <div>Loading build history...</div>;

    return (
        <div className="module-container">
            <h1>Cloud Build History</h1>
            <table className="data-table">
                <thead>
                    <tr>
                        <th>Build ID</th>
                        <th>Status</th>
                        <th>Source</th>
                        <th>Ref</th>
                        <th>Commit</th>
                    </tr>
                </thead>
                <tbody>
                    {builds.map(build => (
                        <tr key={build.id}>
                            <td><code>{build.id}</code></td>
                            <td>
                                <span className={`status-badge ${build.status === '成功' ? 'ok' : 'error'}`}>
                                    {build.status}
                                </span>
                            </td>
                            <td>{build.source}</td>
                            <td>{build.ref}</td>
                            <td><code>{build.commit}</code></td>
                        </tr>
                    ))}
                </tbody>
            </table>

            <style>{`
                .module-container { padding: 20px; }
                .data-table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
                .data-table th, .data-table td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #edf2f7; }
                .data-table th { background: #f7fafc; font-weight: 600; color: #4a5568; }
                .status-badge { padding: 4px 8px; border-radius: 99px; font-size: 12px; font-weight: 500; }
                .status-badge.ok { background: #c6f6d5; color: #22543d; }
                .status-badge.error { background: #fed7d7; color: #822727; }
            `}</style>
        </div>
    );
};

export default BuildsView;
