// dashboard/src/modules/workflows/View.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { getStatusClass } from '$lib/utils/formatters';
    import { getConsoleUrl } from '$lib/utils/consoleLinks';

    let data = $state<{ workflows: any[], executions: any[] } | null>(null);
    let loading = $state(true);

    onMount(async () => {
        try {
            const res = await fetch('/api/modules/workflows/index');
            data = await res.json();
        } catch (err) {
            console.error('Workflows fetch error:', err);
        } finally {
            loading = false;
        }
    });

    function getDotClass(status: string) {
        const cls = getStatusClass(status);
        if (cls === 'status-success') return 'bg-google-green';
        if (cls === 'status-error') return 'bg-google-red';
        if (cls === 'status-warning') return 'bg-google-amber-dark';
        if (cls === 'status-blue') return 'bg-google-blue';
        return 'bg-google-gray-500';
    }

    const firstWorkflow = $derived(data?.workflows?.[0]);
    const latestExec = $derived(data?.executions?.[0]);
</script>

<div>
    {#if loading}
        <div class="text-google-gray-500 text-[13px] text-center py-6">読み込み中...</div>
    {:else if data}
        <!-- Workflow Detail Box (Top Summary) -->
        {#if firstWorkflow}
            <div class="border border-google-gray-300 rounded-lg p-4 mb-3 bg-white">
                <div class="flex justify-between items-center mb-3 text-[12px] text-google-gray-500">
                    <div>ワークフロー: <a href={getConsoleUrl('workflow', firstWorkflow)} target="_blank" rel="noopener" class="text-google-blue font-medium hover:underline">{firstWorkflow.name}</a></div>
                    {#if latestExec}
                        <div class="flex items-center gap-2">
                            現在状態: 
                            <span class="inline-flex items-center gap-1.5 font-medium {getStatusClass(latestExec.status)}">
                                <span class="w-2.5 h-2.5 rounded-full {getDotClass(latestExec.status)}"></span>
                                {latestExec.status === '成功' ? '正常' : latestExec.status}
                            </span>
                        </div>
                    {/if}
                </div>
                <div class="grid grid-cols-2 md:grid-cols-4 gap-3 text-[12px] text-google-gray-500">
                    <div>
                        <div class="mb-1">場所</div>
                        <div class="text-[13px] text-google-gray-900">{firstWorkflow.location}</div>
                    </div>
                    <div>
                        <div class="mb-1">最新のリビジョン</div>
                        <div class="text-[13px] text-google-gray-900">{firstWorkflow.revision}</div>
                    </div>
                    <div>
                        <div class="mb-1">直近実行</div>
                        <div class="text-[13px] text-google-gray-900">{latestExec ? latestExec.created : '—'}</div>
                    </div>
                    <div>
                        <div class="mb-1">ラベル</div>
                        <div class="text-[13px] text-google-gray-900">{firstWorkflow.labels || '—'}</div>
                    </div>
                </div>
            </div>
        {/if}

        <!-- Executions Table -->
        <div class="bg-white border border-google-gray-300 rounded-lg overflow-hidden mb-6 shadow-sm">
            <div class="flex justify-between items-center px-4 py-3 border-b border-google-gray-200 bg-google-gray-50/50">
                <h2 class="text-sm font-medium text-google-gray-900 m-0">実行履歴</h2>
            </div>
            <div class="p-0 overflow-x-auto">
                <table class="w-full text-left text-[13px] text-google-gray-700 border-collapse">
                    <thead class="bg-google-gray-50">
                        <tr>
                            <th class="px-4 py-2.5 border-b border-google-gray-200 font-medium text-google-gray-500 whitespace-nowrap">状態</th>
                            <th class="px-4 py-2.5 border-b border-google-gray-200 font-medium text-google-gray-500 whitespace-nowrap">実行 ID</th>
                            <th class="px-4 py-2.5 border-b border-google-gray-200 font-medium text-google-gray-500 whitespace-nowrap">リビジョン</th>
                            <th class="px-4 py-2.5 border-b border-google-gray-200 font-medium text-google-gray-500 whitespace-nowrap">作成日時</th>
                            <th class="px-4 py-2.5 border-b border-google-gray-200 font-medium text-google-gray-500 whitespace-nowrap">開始時刻</th>
                            <th class="px-4 py-2.5 border-b border-google-gray-200 font-medium text-google-gray-500 whitespace-nowrap">終了時間</th>
                        </tr>
                    </thead>
                    <tbody>
                        {#each data.executions as ex}
                            <tr class="border-b border-google-gray-200 hover:bg-google-gray-50 last:border-b-0">
                                <td class="px-4 py-3 align-top whitespace-nowrap">
                                    <div class="flex items-center gap-2">
                                        <span class="w-2.5 h-2.5 rounded-full {getDotClass(ex.status)}"></span>
                                        <span class="inline-block px-2.5 py-1 rounded-full bg-google-gray-200 text-[11px] font-medium text-google-gray-500">{ex.stepName || 'exec'}</span>
                                        <span class="text-[12px] font-medium {getStatusClass(ex.status)}">{ex.status}</span>
                                    </div>
                                </td>
                                <td class="px-4 py-3 align-top whitespace-nowrap">
                                    <a href={getConsoleUrl('execution', ex)} target="_blank" rel="noopener" class="text-google-blue hover:underline">{ex.executionId}</a>
                                </td>
                                <td class="px-4 py-3 align-top whitespace-nowrap">{ex.revision}</td>
                                <td class="px-4 py-3 align-top whitespace-nowrap">{ex.created}</td>
                                <td class="px-4 py-3 align-top whitespace-nowrap">{ex.started}</td>
                                <td class="px-4 py-3 align-top whitespace-nowrap">{ex.ended}</td>
                            </tr>
                        {/each}
                    </tbody>
                </table>
            </div>
        </div>
    {/if}
</div>

// dashboard/client/src/modules/workflows/View.tsx
import React, { useEffect, useState } from 'react';

interface Workflow {
    name: string;
    location: string;
    revision: string;
    updated: string;
}

interface Execution {
    executionId: string;
    status: string;
    started: string;
    stepName: string;
}

const WorkflowsView: React.FC = () => {
    const [data, setData] = useState<{ workflows: Workflow[], executions: Execution[] } | null>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetch('/api/modules/workflows')
            .then(res => res.json())
            .then(json => {
                setData(json);
                setLoading(false);
            })
            .catch(err => {
                console.error('Workflows fetch error:', err);
                setLoading(false);
            });
    }, []);

    if (loading) return <div>Loading Workflows...</div>;
    if (!data) return <div>No data available.</div>;

    return (
        <div className="module-container">
            <h1>Workflows</h1>
            <h3>Active Workflows</h3>
            <table className="data-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Region</th>
                        <th>Revision</th>
                        <th>Last Updated</th>
                    </tr>
                </thead>
                <tbody>
                    {data.workflows.map(wf => (
                        <tr key={wf.name}>
                            <td>{wf.name}</td>
                            <td>{wf.location}</td>
                            <td>{wf.revision}</td>
                            <td>{wf.updated}</td>
                        </tr>
                    ))}
                </tbody>
            </table>

            <h3>Recent Executions</h3>
            <table className="data-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Status</th>
                        <th>Step</th>
                        <th>Started</th>
                    </tr>
                </thead>
                <tbody>
                    {data.executions.map(ex => (
                        <tr key={ex.executionId}>
                            <td>{ex.executionId.substring(0, 8)}...</td>
                            <td>
                                <span className={`status-badge ${ex.status === '成功' ? 'ok' : 'error'}`}>
                                    {ex.status}
                                </span>
                            </td>
                            <td>{ex.stepName}</td>
                            <td>{ex.started}</td>
                        </tr>
                    ))}
                </tbody>
            </table>

            <style>{`
                .module-container { padding: 20px; }
                .data-table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 30px; }
                .data-table th, .data-table td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #edf2f7; }
                .data-table th { background: #f7fafc; font-weight: 600; color: #4a5568; }
                .status-badge { padding: 4px 8px; border-radius: 99px; font-size: 12px; font-weight: 500; }
                .status-badge.ok { background: #c6f6d5; color: #22543d; }
                .status-badge.error { background: #fed7d7; color: #822727; }
            `}</style>
        </div>
    );
};

export default WorkflowsView;
