// dashboard/client/src/modules/cloud-run/View.tsx
import React, { useEffect, useState } from 'react';

interface CloudRunService {
    name: string;
    status: string;
    region: string;
    uri: string;
}

const CloudRunView: React.FC = () => {
    const [services, setServices] = useState<CloudRunService[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetch('/api/modules/cloud-run/services')
            .then(res => res.json())
            .then(data => {
                setServices(data);
                setLoading(false);
            })
            .catch(err => {
                console.error('Cloud Run fetch error:', err);
                setLoading(false);
            });
    }, []);

    if (loading) return <div>Loading Cloud Run services...</div>;

    return (
        <div className="module-container">
            <h1>Cloud Run Services</h1>
            <table className="data-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Status</th>
                        <th>Region</th>
                        <th>URL</th>
                    </tr>
                </thead>
                <tbody>
                    {services.map(svc => (
                        <tr key={svc.name}>
                            <td>{svc.name}</td>
                            <td>
                                <span className={`status-badge ${svc.status === '正常' ? 'ok' : 'error'}`}>
                                    {svc.status}
                                </span>
                            </td>
                            <td>{svc.region}</td>
                            <td><a href={svc.uri} target="_blank" rel="noreferrer">Open</a></td>
                        </tr>
                    ))}
                </tbody>
            </table>

            <style>{`
                .module-container { padding: 20px; }
                .data-table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
                .data-table th, .data-table td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #edf2f7; }
                .data-table th { background: #f7fafc; font-weight: 600; color: #4a5568; }
                .status-badge { padding: 4px 8px; border-radius: 99px; font-size: 12px; font-weight: 500; }
                .status-badge.ok { background: #c6f6d5; color: #22543d; }
                .status-badge.error { background: #fed7d7; color: #822727; }
            `}</style>
        </div>
    );
};

export default CloudRunView;

// dashboard/src/lib/modules/cloud-run/View.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { getStatusClass } from '$lib/utils/formatters';
    import * as Icons from 'lucide-svelte';

    let services = $state<any[]>([]);
    let loading = $state(true);

    async function fetchServices() {
        loading = true;
        try {
            const res = await fetch('/api/modules/cloud-run/services');
            services = await res.json();
        } catch (err) {
            console.error('Cloud Run fetch error:', err);
        } finally {
            loading = false;
        }
    }

    onMount(fetchServices);
</script>

<div class="cloud-run-container">
    <div class="flex justify-between items-center mb-6">
        <h2 class="text-lg font-medium text-gray-800">サービス一覧 (Run v2)</h2>
        <button class="btn-primary flex items-center gap-2 text-sm" onclick={fetchServices}>
            <Icons.RotateCw size={14} />
            <span>更新</span>
        </button>
    </div>
    
    {#if loading}
        <div class="animate-pulse space-y-4">
            {#each Array(3) as _}
                <div class="h-16 bg-gray-50 rounded border border-gray-100"></div>
            {/each}
        </div>
    {:else}
        <div class="card overflow-hidden">
            <table class="data-table">
                <thead>
                    <tr>
                        <th>サービス名</th>
                        <th>ステータス</th>
                        <th>リージョン</th>
                        <th>認証</th>
                        <th>URL</th>
                    </tr>
                </thead>
                <tbody>
                    {#each services as svc}
                        <tr>
                            <td class="font-medium text-gray-900">{svc.name}</td>
                            <td>
                                <span class="{getStatusClass(svc.status)}">
                                    {svc.status}
                                </span>
                            </td>
                            <td class="text-sm text-gray-600">{svc.region}</td>
                            <td class="text-xs text-gray-500">{svc.authentication}</td>
                            <td>
                                <a href={svc.uri} target="_blank" rel="noreferrer" class="text-blue-600 hover:text-blue-800 flex items-center gap-1">
                                    <Icons.ExternalLink size={14} />
                                    <span>開く</span>
                                </a>
                            </td>
                        </tr>
                    {/each}
                </tbody>
            </table>
        </div>
    {/if}
</div>
