// dashboard/client/src/modules/workflows/View.tsx
import React, { useEffect, useState } from 'react';

interface Workflow {
    name: string;
    location: string;
    revision: string;
    updated: string;
}

interface Execution {
    executionId: string;
    status: string;
    started: string;
    stepName: string;
}

const WorkflowsView: React.FC = () => {
    const [data, setData] = useState<{ workflows: Workflow[], executions: Execution[] } | null>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetch('/api/modules/workflows')
            .then(res => res.json())
            .then(json => {
                setData(json);
                setLoading(false);
            })
            .catch(err => {
                console.error('Workflows fetch error:', err);
                setLoading(false);
            });
    }, []);

    if (loading) return <div>Loading Workflows...</div>;
    if (!data) return <div>No data available.</div>;

    return (
        <div className="module-container">
            <h1>Workflows</h1>
            <h3>Active Workflows</h3>
            <table className="data-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Region</th>
                        <th>Revision</th>
                        <th>Last Updated</th>
                    </tr>
                </thead>
                <tbody>
                    {data.workflows.map(wf => (
                        <tr key={wf.name}>
                            <td>{wf.name}</td>
                            <td>{wf.location}</td>
                            <td>{wf.revision}</td>
                            <td>{wf.updated}</td>
                        </tr>
                    ))}
                </tbody>
            </table>

            <h3>Recent Executions</h3>
            <table className="data-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Status</th>
                        <th>Step</th>
                        <th>Started</th>
                    </tr>
                </thead>
                <tbody>
                    {data.executions.map(ex => (
                        <tr key={ex.executionId}>
                            <td>{ex.executionId.substring(0, 8)}...</td>
                            <td>
                                <span className={`status-badge ${ex.status === '成功' ? 'ok' : 'error'}`}>
                                    {ex.status}
                                </span>
                            </td>
                            <td>{ex.stepName}</td>
                            <td>{ex.started}</td>
                        </tr>
                    ))}
                </tbody>
            </table>

            <style>{`
                .module-container { padding: 20px; }
                .data-table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 30px; }
                .data-table th, .data-table td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #edf2f7; }
                .data-table th { background: #f7fafc; font-weight: 600; color: #4a5568; }
                .status-badge { padding: 4px 8px; border-radius: 99px; font-size: 12px; font-weight: 500; }
                .status-badge.ok { background: #c6f6d5; color: #22543d; }
                .status-badge.error { background: #fed7d7; color: #822727; }
            `}</style>
        </div>
    );
};

export default WorkflowsView;

// dashboard/src/lib/modules/workflows/View.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { getStatusClass } from '$lib/utils/formatters';
    import * as Icons from 'lucide-svelte';

    let data = $state<{ workflows: any[], executions: any[] } | null>(null);
    let loading = $state(true);

    async function fetchData() {
        loading = true;
        try {
            const res = await fetch('/api/modules/workflows/all');
            data = await res.json();
        } catch (err) {
            console.error('Workflows fetch error:', err);
        } finally {
            loading = false;
        }
    }

    onMount(fetchData);
</script>

<div class="workflows-container">
    {#if loading}
        <div class="space-y-8 animate-pulse">
            {#each Array(2) as _}
                <div class="h-32 bg-gray-50 rounded border border-gray-100"></div>
            {/each}
        </div>
    {:else if data}
        <section class="mb-8">
            <div class="flex justify-between items-center mb-4">
                <h2 class="text-lg font-medium text-gray-800">ワークフロー定義</h2>
                <button class="btn-primary flex items-center gap-2 text-sm" onclick={fetchData}>
                    <Icons.RotateCw size={14} />
                    <span>更新</span>
                </button>
            </div>
            <div class="card overflow-hidden">
                <table class="data-table">
                    <thead>
                        <tr>
                            <th>ワークフロー名</th>
                            <th>ロケーション</th>
                            <th>リビジョン</th>
                            <th>最終更新</th>
                        </tr>
                    </thead>
                    <tbody>
                        {#each data.workflows as wf}
                            <tr>
                                <td class="font-medium text-gray-900">{wf.name}</td>
                                <td>{wf.location}</td>
                                <td class="text-xs font-mono text-gray-500">{wf.revision}</td>
                                <td class="text-sm text-gray-600">{wf.updated}</td>
                            </tr>
                        {/each}
                    </tbody>
                </table>
            </div>
        </section>

        <section>
            <h2 class="text-lg font-medium text-gray-800 mb-4">直近の実行履歴</h2>
            <div class="card overflow-hidden">
                <table class="data-table">
                    <thead>
                        <tr>
                            <th>実行 ID</th>
                            <th>ステータス</th>
                            <th>現在のステップ</th>
                            <th>開始時刻</th>
                        </tr>
                    </thead>
                    <tbody>
                        {#each data.executions as ex}
                            <tr>
                                <td class="text-xs text-blue-600 font-mono font-medium">{ex.executionId}</td>
                                <td>
                                    <span class="{getStatusClass(ex.status)}">
                                        {ex.status}
                                    </span>
                                </td>
                                <td class="text-sm text-gray-600">{ex.stepName}</td>
                                <td class="text-sm text-gray-500 font-mono">{ex.started}</td>
                            </tr>
                        {/each}
                    </tbody>
                </table>
            </div>
        </section>
    {:else}
        <div class="error-message">
            ワークフロー情報の取得に失敗しました。
        </div>
    {/if}
</div>
