// dashboard/client/src/modules/compute/View.tsx
import React, { useEffect, useState } from 'react';

interface Instance {
    name: string;
    status: string;
    zone: string;
    internalIp: string;
    externalIp: string;
    description: string;
}

const ComputeView: React.FC = () => {
    const [instances, setInstances] = useState<Instance[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetch('/api/modules/compute')
            .then(res => res.json())
            .then(data => {
                setInstances(data);
                setLoading(false);
            })
            .catch(err => {
                console.error('Compute fetch error:', err);
                setLoading(false);
            });
    }, []);

    if (loading) return <div>Loading GCE instances...</div>;

    return (
        <div className="module-container">
            <h1>Compute Engine</h1>
            <table className="data-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Status</th>
                        <th>Zone</th>
                        <th>External IP</th>
                        <th>Internal IP</th>
                    </tr>
                </thead>
                <tbody>
                    {instances.map(inst => (
                        <tr key={inst.name}>
                            <td>
                                <strong>{inst.name}</strong><br/>
                                <small>{inst.description}</small>
                            </td>
                            <td>
                                <span className={`status-badge ${inst.status === '稼働中' ? 'ok' : 'error'}`}>
                                    {inst.status}
                                </span>
                            </td>
                            <td>{inst.zone}</td>
                            <td>{inst.externalIp}</td>
                            <td>{inst.internalIp}</td>
                        </tr>
                    ))}
                </tbody>
            </table>

            <style>{`
                .module-container { padding: 20px; }
                .data-table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
                .data-table th, .data-table td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #edf2f7; }
                .data-table th { background: #f7fafc; font-weight: 600; color: #4a5568; }
                .status-badge { padding: 4px 8px; border-radius: 99px; font-size: 12px; font-weight: 500; }
                .status-badge.ok { background: #c6f6d5; color: #22543d; }
                .status-badge.error { background: #fed7d7; color: #822727; }
                small { color: #888; font-size: 11px; }
            `}</style>
        </div>
    );
};

export default ComputeView;

// dashboard/src/lib/modules/compute/View.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { getStatusClass } from '$lib/utils/formatters';
    import * as Icons from 'lucide-svelte';

    let instances = $state<any[]>([]);
    let loading = $state(true);

    async function fetchInstances() {
        loading = true;
        try {
            const res = await fetch('/api/modules/compute/index');
            instances = await res.json();
        } catch (err) {
            console.error('Compute fetch error:', err);
        } finally {
            loading = false;
        }
    }

    onMount(fetchInstances);
</script>

<div class="compute-container">
    <div class="flex justify-between items-center mb-6">
        <h2 class="text-lg font-medium text-gray-800">インスタンス一覧</h2>
        <button class="btn-primary flex items-center gap-2 text-sm" onclick={fetchInstances}>
            <Icons.RotateCw size={14} />
            <span>更新</span>
        </button>
    </div>
    
    {#if loading}
        <div class="animate-pulse space-y-4">
            {#each Array(2) as _}
                <div class="h-20 bg-gray-50 rounded border border-gray-100"></div>
            {/each}
        </div>
    {:else}
        <div class="card overflow-hidden">
            <table class="data-table">
                <thead>
                    <tr>
                        <th>インスタンス名</th>
                        <th>ステータス</th>
                        <th>ゾーン</th>
                        <th>IP アドレス</th>
                    </tr>
                </thead>
                <tbody>
                    {#each instances as inst}
                        <tr>
                            <td>
                                <div class="font-medium text-gray-900">{inst.name}</div>
                                <div class="text-xs text-gray-400 mt-0.5">{inst.description}</div>
                            </td>
                            <td>
                                <span class="{getStatusClass(inst.status)}">
                                    {inst.status}
                                </span>
                            </td>
                            <td class="text-sm text-gray-600 font-mono">{inst.zone}</td>
                            <td>
                                <div class="flex flex-col gap-1">
                                    <div class="flex items-center gap-2">
                                        <span class="text-[10px] font-bold text-gray-400 w-8 uppercase">Ext:</span>
                                        <span class="text-xs font-mono text-gray-700">{inst.externalIp || 'N/A'}</span>
                                    </div>
                                    <div class="flex items-center gap-2">
                                        <span class="text-[10px] font-bold text-gray-400 w-8 uppercase">Int:</span>
                                        <span class="text-xs font-mono text-gray-500">{inst.internalIp || 'N/A'}</span>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {/each}
                </tbody>
            </table>
        </div>
    {/if}
</div>
